Commit
mustafaseytasanov/MapNew pull request #1
Opened 2022-02-08 11:23 UTC by mustafaseytasanov

2022-02-08 13:47 UTC, dkorkin requested changes

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/AppDelegate.swift
> +        var isLoggedIn = userDefaults.bool(forKey: "isLoggedIn")
из менеджера надо достать

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/Cells/TableViewFirstCell.swift
> +final class TableViewFirstCell: UITableViewCell {
First она единственна и она inPputCell

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/Cells/TableViewFirstCell.swift
> +        contentView.addSubview(colorView)
в хедер таблицы

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/DescriptionViewController.swift
> +        //self.navigationItem.leftBarButtonItem = UIBarButtonItem(barButtonSystemItem: .fixedSpace, target: self, action: #selector(funct))
комментарии

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/DescriptionViewController.swift
> +        cell.configure(with: "")
зачем?

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/LoginViewController.swift
> +        if flag == 1 {
разные датасорсы

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/LoginViewController.swift
> +                    cell.configure(with: .email)
indexPath.row

2022-02-08 13:47 UTC, dkorkin commented on Map/Map/MapViewController.swift
> +        annotation.title = "School"
строки локализовать

2022-02-21 11:08 UTC, mustafaseytasanov commented
.

2022-02-21 11:09 UTC, closed without merging